#!/bin/bash

# Allow Python version to be overridden via environment variable
THETACODE_PYTHON_VERSION="${THETACODE_PYTHON_VERSION:-/usr/bin/python3}"
THETACODE_PYTHON_SCRIPT="/opt/thetacode/initialize_minecraft_fabric_mod.py"

# Execute
"$THETACODE_PYTHON_VERSION" "$THETACODE_PYTHON_SCRIPT" "$@"
