#!/bin/bash

# Allow Python version to be overridden via environment variable
PYTHON_VERSION="/usr/bin/python3"
PYTHON_SCRIPT="/opt/thetacode/webpage_to_markdown.py"

# Execute
"$PYTHON_VERSION" "$PYTHON_SCRIPT" "$@"
